(define (problem blocksworld01)
    (:domain blocksworld)
    (:objects BlockA BlockB BlockC Hand)
    (:init 
        (on BlockA BlockC) 
        (ontable BlockC) 
        (ontable BlockB) 
        (clear BlockC) 
        (clear BlockB) 
        (handempty)
    )
    (:goal
        (and
            (clear BlockA)
            (on BlockA BlockB)
            (on BlockB BlockC)
            (ontable BlockC)
        )
    )
)
