(define (problem ghost-01)
   (:domain ghost)
   (:objects l1 l2 l3 l4 - location)
   ;; define the initial situation
   (:init (connected l1 l2)
          (connected l1 l3)
          (connected l2 l3)
          (connected l1 l4)
          (connected l2 l1)
          (connected l3 l1)
          (connected l3 l2)
          (connected l4 l1)
          (pacmanAt l1)
          (ghostAt l3)
   )
   (:goal (and (not(pacmanAt l1))
   ))
)