python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
python capture.py -r myTeam -b myTeamDQ5 -q 
