python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
python capture.py -r myTeam16 -b myTeam -q 
